### PR TITLE
Filament v3

### PR DESCRIPTION
**Pull request by thapaPrabhat**

### CODE REVIEW

**Comment by invaders-xx** [comment]
@thapaPrabhat , did you test it with V3 ?

**Comment by aiysya** [comment]
> @thapaPrabhat , did you test it with V3 ?

Do you have plans to support V3?

**Comment by thapaPrabhat** [comment]
@invaders-xx  Yes, I checked the basic functionalities like, display board, listing records, sorting, changing status etc.

Background Colors are not working may be because of new Theme in Filament.

**Comment by ziming** [comment]
Running php artisan view:cache as part of deployment will throw this error

> Unable to locate a class or view for component [filament::form].

I think filament::form blade component no longer exist in filament v3 that's why

edit-modal-record.blade.php use this blade component

**Pull request closed without merging**
